### PR TITLE
Fixed typo preventing using paid subscription key

### PR DESCRIPTION
**Pull request by chidochipotle**
This module worked fine with free keys but for my paid subscription key I got and error,
Changing "v1" by "v1.0" on request urls fixed it.

### CODE REVIEW

**Comment by chidochipotle** [comment]
Updated requests urls, all tests pass ok, so I uncommented some tests that seemed the fail previously. Also added analyze so it can return Tags, Description features and Celebrities details.

**Comment by irjudson** [comment]
Hey! I'd love to merge this, I didn't notice the PR until now (I apologize). Give me a few hours to figure out new keys for travis so I can tell it passes CI and then I'll merge (if it passes! :) )

**Comment by irjudson** [comment]
I've updated all my API keys in travis, but for some reason they're not being found in your PR auto-build. I'm still trying to track this down. I'm happy to have suggestions :)

**Review by irjudson — CHANGES_REQUESTED** [review]
I would try reverting the travis.yml file changes, since something in setup is failing and it's not able to find the shell variables. This makes it more likely a setup problem than a code problem further down the line.

Just a thought.

**Comment by chidochipotle** [comment]
Hi Ivan !
You are back ! :-)
Working on your comments above !
Will get back to you shortly.

**Comment by chidochipotle** [comment]
Hi Ivan !

Nice to meet you !
- Failed tests
  I would double check your keys in the Microsoft Testing API console, it looks like Microsoft Cognitive Services (MSC) is not accepting your keys in your travis logs.
  My travis build was successful:
  https://travis-ci.org/chidochipotle/microsoft-cognitive-vision
- Naming
  As you can see, I took the liberty to rename my fork "microsoft-cognitive-vision" to avoid confusion, I can go back to "oxford" if you think it's prudent.  Actually, I just realized that I used the typically forbidden '-' (dash), so I should rename it to something more pythonic like "ms_cognitive_vision"
- Pull Request
  I am totally new to github, so I don't know how to make a "correct pull request".
  I didn't mean for my first pull request to span all my following commits but that's the way github works ...
  Thus i would suggest for you to to merge up to:
  [Placing encrypted keys for travis ci in repository settings            76c9e70](https://github.com/irjudson/oxford/pull/1/commits/76c9e705cc293bd2464f3532f1abba11458e544b)
- Branches
  I haven't even tested my last commit for pypi deployment
  Just created a develop branch on my fork will work on the develop branch from now on.
  Will start using the github branching conventions.
  http://danielkummer.github.io/git-flow-cheatsheet/
  Sounds ok ?
- Pypi
  I am just setting up the automated pip build. 
  Since you are the owner, you may want to deploy pypi packages from your repository.
  What would you prefer:
- Deploy from your repository ( Check http://5minutes.youkidea.com/howto-deploy-python-package-on-pypi-with-github-and-travis.html )
- Or I can commit my .travis.yml it in a separate branch. That way that you don't have to merge a travis that contains my user info and  I can still deploy pypi from my repo.

**Comment by irjudson** [comment]
I'll take a look at my key issue, it might be because of something silly.

I'll also publish to PyPi so you don't have to (then any PR's can get deployed fast).

Naming is tough, I'll talk to internal folks and see if there's something we should do to be "appropriate" to the services :)

thanks!

**Comment by chidochipotle** [comment]
Sounds great, any issues if I start implementing data models for each class so users don't have to deal with JSON and can use objects ?

Something along the lines of:
Face.result.faceId
Face.result.faceId.faceRectangle
Face.result.faceId.faceRectangle.width
etc ...

**Comment by irjudson** [comment]
Seems like a sane approach, does it make sense to use properties and then
make sure they're updated in the send/receive so they don't get stale?

--Ivan

Ivan R. Judson
irjudson.org
(425) 679-1375

On Tue, Oct 4, 2016 at 12:58 PM, Daniel Kornhauser <notifications@github.com

**Comment by chidochipotle** [comment]
Hi Ivan:

I released 0.1.4 by mistake, I was trying to make my own pypi release.
Feel free to overwrite my release, really surprised how easy it's to upload to pypi ...

**Comment by chidochipotle** [comment]
Hi Ivan:
Here is a link to the [FaceModel approach](https://gist.github.com/chidochipotle/0934832064da5740de8c072deab32aea) I would take.

Can you take a look at the link and confirm we are on the same page ?

Thanks.

**Pull request closed without merging**
